-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
WHERE I.ITEM_ID NOT IN (
    SELECT T.PARENT_ITEM_ID
    FROM ITEM_TREE T
    WHERE T.PARENT_ITEM_ID IS NOT NULL
)
ORDER BY I.ITEM_ID DESC;

/*
EXISTS 구문
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
WHERE NOT EXISTS (
    SELECT 1
    FROM ITEM_TREE T
    WHERE T.PARENT_ITEM_ID = I.ITEM_ID
)
ORDER BY I.ITEM_ID DESC;
*/