-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
WHERE R.FAVORITES = (SELECT MAX(FAVORITES) FROM REST_INFO WHERE FOOD_TYPE = R.FOOD_TYPE)
ORDER BY R.FOOD_TYPE DESC

/*
GROUP BY는 “집계 결과”만 보여줄 수 있고, 그룹 내에서 특정 행을 뽑는 기능은 없음.
이럴 때는 서브 쿼리 활용.
*/