-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A
         JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(SECOND, B.DATETIME, A.DATETIME) DESC
    LIMIT 2;

/*

TIMESTAMPDIFF(SECOND, B.DATETIME, A.DATETIME)
→ 입소일과 출소일의 차이를 초 단위로 계산

LIMIT 2
→ 상위 두 개만 출력

*/