
-- 코드를 작성해주세요
SELECT CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER(DIFFERENTIATION_DATE)
ORDER BY QUARTER(DIFFERENTIATION_DATE) ASC;

-- QUARTER(날짜컬럼)으로 날짜 데이터를 분기별로 나눌 수 있음.

/*
SELECT CASE QUARTER(DIFFERENTIATION_DATE)
          WHEN 1 THEN '1Q'
          WHEN 2 THEN '2Q'
          WHEN 3 THEN '3Q'
          WHEN 4 THEN '4Q'
      END,   -- CASE로 조건 분기 시작, END로 닫아야 함
      COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER(DIFFERENTIATION_DATE)
ORDER BY QUARTER(DIFFERENTIATION_DATE) ASC;

CASE : 조건문 시작
WHEN ... THEN ... : 조건에 맞는 결과 반환
END : 조건문 종료 (필수)
즉, CASE는 IF 같은 조건문이고, END는 그 조건문을 닫는 역할이라고 주석에 달아두면 깔끔합니다.

*/