
SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC

/*
 소수점 자리 반올림
 ROUND(SUM(D_BETWEEN_DIST), 1) -> 소수점 첫째 자리까지 나옴

 단위 붙이기
 SELECT CONCAT(ROUND(123.456, 2), ' kg') AS result;
 */